name: Release image

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  id-token: write
  contents: read

jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WEBSIGHT_RELEASES_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_WEBSIGHT_RELEASES_RELEASE_DEPLOY_SA }}
      -
        name: Setup docker auth
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev
      - 
        name: Set up QEMU # https://github.com/docker/buildx/issues/499
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags:  europe-west1-docker.pkg.dev/websight-io/websight-docker-releases/cypress-jdk-maven:${{ github.ref_name }}